
option(FORCE_QT5 "Force Building With Qt5 Even If Qt6 Is Present")
if(FORCE_QT5)
	find_package(Qt5 REQUIRED COMPONENTS Core)
	set(QT_VERSION_MAJOR 5)
else()
	find_package(Qt6 COMPONENTS Core)
	if(Qt6_FOUND)
		set(QT_VERSION_MAJOR 6)
	else()
		find_package(Qt5 REQUIRED COMPONENTS Core)
		set(QT_VERSION_MAJOR 5)
	endif()
endif()

if(DEFINED QT_VERSION_MAJOR)
	message("Configured With Qt ${QT_VERSION_MAJOR}")
else()
	message(FATAL_ERROR "No compatible version of Qt was found")
endif()
