
macro(DETECT_ARCHITECTURE VARIABLE)
	if((${CMAKE_SYSTEM_PROCESSOR} MATCHES "i[3456]86") OR (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64") OR (${CMAKE_SYSTEM_PROCESSOR} MATCHES "[aA][mM][dD]64"))
		set(${VARIABLE} x86)
	endif()

	if((${CMAKE_SYSTEM_PROCESSOR} MATCHES "armv[0-9]+"))
		set(${VARIABLE} arm)
	endif()
endmacro()
